### ISSUE TITLE
Calibration using ClimateIndicator emissions

### ISSUE THREAD

**Issue by fracamil** [chrisroadmap/fair-calibrate#104]
As a reminder for further works, it could be useful to have a calibration using the emissions and forcing time series used to update Climate Change Indicators. This basis would allow to estimate future temperature anomaly, concentrations and forcing based on actual emissions, and be more representative. Not urgent, off course.

**Comment by chrisroadmap** [comment]
This is actually in progress already. Some of the historical emissions from updated datasets differ substantially from CMIP6, so getting the emissions to concentration step correct is causing headaches.

**Comment by fracamil** [comment]
Well. Thanks a lot for the answer. I hope this will be available some time. If not, not an issue. I will close this issue in GitHbub, then.
