### ISSUE TITLE
1pct runs

### ISSUE THREAD

**Issue by chrisroadmap** [chrisroadmap/fair-calibrate#95]
need to set `forcing_reference_concentration` and `baseline_concentration` to 1850 values.

**Comment by aipartanen** [comment]
Calculating the atmospheric mass change based on doubling of CO2 from 1850-value yields  284.3169988*2.13=605.595 GtC. But as the temperature increase used in TCRE calculated on year 70 (1920) value, I think also respective the concentration change should be used. This would yield (570.5569382-284.3169988)*2.13 = 609.69107 Gt C.

**Comment by chrisroadmap** [comment]
Yes, that's correct - will be fixed in v1.2 (also for 4xCO2)
